# Site settings
title:TOBB ETU Mobile Robotics Systems Laboratory
email:etumors@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Söğütözü Avenue 43, Söğütözü, Ankara, 06560 Turkey
baseurl:"" # the subpath of your site, e.g. /blog/
<<<<<<< HEAD
url:http://mors.etu.edu.tr # the base hostname & protocol for your site
twitter_username:ETUmors # changed from MORS_Lab to ETUmors
======= #commented out
url:http://yourdomain.com # the base hostname & protocol for your site
twitter_username: ETUmors
>>>>>>> FETCH_HEAD
github_username:mors-lab

# Build settings
markdown:kramdown
